export default {
  index: 'Overview',
  authentication: 'Authentication',
  'api-keys': 'API Keys',
  roles: 'Roles',
  users: 'Users',
  categories: 'Categories',
  foods: 'Foods',
  ingredients: 'Ingredients',
  orders: 'Orders',
  reports: 'Reports',
  banners: 'Banners',
  'order-instructions': 'Order Instructions',
  printers: 'Printers',
  'cash-registers': 'Cash Registers',
  events: 'Events (SSE)',
}
